version: "3"
services:
  app:
    image: alexandersus/nodejs-airport:v1
    container_name: nodejs-airport 
    build: 
      context: .
      target: development 
    command: npm run start:dev
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/app
    env_file: 
    - .env
    depends_on:
      - redis
      - db
    restart: unless-stopped
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
  db:
    image: postgres:15-alpine
    container_name: airport-db 
    restart: always 
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  pgadmin:
      image: dpage/pgadmin4:7.0
      ports:
        - "8080:80"
      volumes:
        - /data/pgadmin:/root/.pgadmin
      depends_on: 
        - db
      env_file:
        - .env
volumes:
  airportapp:
