version: "3"
services:
  app:
    image: alexandersus/nodejs-airport:v1
    container_name: nodejs-airport 
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/app
    env_file: 
    - .env
    depends_on:
      - redis
    restart: unless-stopped
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
        - redis