INSERT INTO airport (name, iata, city, country) VALUES
 ('Heathrow Airport','LHR', 'London', 'UK')
,('Dubai International Airport','DXB', 'Dubai', 'UAE')
,('Charles de Gaulle Airport','CDG', 'Paris', 'France')
,('Los Angeles International Airport','LAX', 'Los Angeles', 'USA')
,('Frankfurt Airport','FRA', 'Frankfurt', 'Germany')
,('Hong Kong International Airport','HKG', 'Hong Kong', 'China')
,('Narita International Airport','NRT', 'Tokyo', 'Japan')
,('Sydney Kingsford Smith Airport','SYD', 'Sydney', 'Australia')
,('O''Hare International Airport','ORD', 'Chicago', 'USA')
,('Beijing Capital International Airport','PEK', 'Beijing', 'China')
,('Amsterdam Airport Schiphol','AMS', 'Amsterdam', 'Netherlands')
,('Toronto Pearson International Airport','YYZ', 'Toronto', 'Canada')
,('Istanbul Atatürk Airport','IST', 'Istanbul', 'Turkey')
,('Incheon International Airport','ICN', 'Seoul', 'South Korea')
,('Shanghai Pudong International Airport','PVG', 'Shanghai', 'China')
,('Indira Gandhi International Airport','DEL', 'New Delhi', 'India')
,('Suvarnabhumi Airport','BKK', 'Bangkok', 'Thailand')
,('Leonardo da Vinci-Fiumicino Airport','FCO', 'Rome', 'Italy')
,('San Francisco International Airport','SFO', 'San Francisco', 'USA')
,('Jorge Chávez International Airport','LIM', 'Lima', 'Peru')
,('Kuala Lumpur International Airport','KUL', 'Kuala Lumpur', 'Malaysia')
,('Copenhagen Airport','CPH', 'Copenhagen', 'Denmark')
,('Vancouver International Airport','YVR', 'Vancouver', 'Canada')
,('Athens International Airport','ATH', 'Athens', 'Greece')
,('Dubai World Central-Al Maktoum International Airport','DWC', 'Dubai', 'UAE')
,('Adolfo Suárez Madrid–Barajas Airport','MAD', 'Madrid', 'Spain')
,('Jomo Kenyatta International Airport','NBO', 'Nairobi', 'Kenya')
,('Hamad International Airport','DOH', 'Doha', 'Qatar')
;
