INSERT INTO city (name, country_name) VALUES 
 ('Sydney', (SELECT name FROM country WHERE name = 'Australia'))
,('Toronto', (SELECT name FROM country WHERE name = 'Canada'))
,('Vancouver', (SELECT name FROM country WHERE name = 'Canada'))
,('Hong Kong', (SELECT name FROM country WHERE name = 'China'))
,('Beijing', (SELECT name FROM country WHERE name = 'China'))
,('Shanghai', (SELECT name FROM country WHERE name = 'China'))
,('Copenhagen', (SELECT name FROM country WHERE name = 'Denmark'))
,('Paris', (SELECT name FROM country WHERE name = 'France'))
,('Frankfurt', (SELECT name FROM country WHERE name = 'Germany'))
,('Athens', (SELECT name FROM country WHERE name = 'Greece'))
,('New Delhi', (SELECT name FROM country WHERE name = 'India'))
,('Rome', (SELECT name FROM country WHERE name = 'Italy'))
,('Tokyo', (SELECT name FROM country WHERE name = 'Japan'))
,('Nairobi', (SELECT name FROM country WHERE name = 'Kenya'))
,('Kuala Lumpur', (SELECT name FROM country WHERE name = 'Malaysia'))
,('Amsterdam', (SELECT name FROM country WHERE name = 'Netherlands'))
,('Lima', (SELECT name FROM country WHERE name = 'Peru'))
,('Doha', (SELECT name FROM country WHERE name = 'Qatar'))
,('Seoul', (SELECT name FROM country WHERE name = 'South Korea'))
,('Madrid', (SELECT name FROM country WHERE name = 'Spain'))
,('Bangkok', (SELECT name FROM country WHERE name = 'Thailand'))
,('Istanbul', (SELECT name FROM country WHERE name = 'Turkey'))
,('Dubai', (SELECT name FROM country WHERE name = 'UAE'))
,('London', (SELECT name FROM country WHERE name = 'UK'))
,('Los Angeles', (SELECT name FROM country WHERE name = 'USA'))
,('Chicago', (SELECT name FROM country WHERE name = 'USA'))
,('San Francisco', (SELECT name FROM country WHERE name = 'USA'))
;
 

