INSERT INTO airport (name, iata, city_id, country_name) VALUES
 ('Heathrow Airport','LHR', (SELECT id FROM city WHERE name = 'London'),(SELECT name FROM country WHERE name = 'UK'))
,('Dubai International Airport','DXB', (SELECT id FROM city WHERE name = 'Dubai'),(SELECT name FROM country WHERE name = 'UAE'))
,('Charles de Gaulle Airport','CDG', (SELECT id FROM city WHERE name = 'Paris'),(SELECT name FROM country WHERE name = 'France'))
,('Los Angeles International Airport','LAX', (SELECT id FROM city WHERE name = 'Los Angeles'),(SELECT name FROM country WHERE name = 'USA'))
,('Frankfurt Airport','FRA', (SELECT id FROM city WHERE name = 'Frankfurt'),(SELECT name FROM country WHERE name = 'Germany'))
,('Hong Kong International Airport','HKG', (SELECT id FROM city WHERE name = 'Hong Kong'),(SELECT name FROM country WHERE name = 'China'))
,('Narita International Airport','NRT', (SELECT id FROM city WHERE name = 'Tokyo'),(SELECT name FROM country WHERE name = 'Japan'))
,('Sydney Kingsford Smith Airport','SYD', (SELECT id FROM city WHERE name = 'Sydney'),(SELECT name FROM country WHERE name = 'Australia'))
,('O''Hare International Airport','ORD', (SELECT id FROM city WHERE name = 'Chicago'),(SELECT name FROM country WHERE name = 'USA'))
,('Beijing Capital International Airport','PEK', (SELECT id FROM city WHERE name = 'Beijing'),(SELECT name FROM country WHERE name = 'China'))
,('Amsterdam Airport Schiphol','AMS', (SELECT id FROM city WHERE name = 'Amsterdam'),(SELECT name FROM country WHERE name = 'Netherlands'))
,('Toronto Pearson International Airport','YYZ', (SELECT id FROM city WHERE name = 'Toronto'),(SELECT name FROM country WHERE name = 'Canada'))
,('Istanbul Atatürk Airport','IST', (SELECT id FROM city WHERE name = 'Istanbul'),(SELECT name FROM country WHERE name = 'Turkey'))
,('Incheon International Airport','ICN', (SELECT id FROM city WHERE name = 'Seoul'),(SELECT name FROM country WHERE name = 'South Korea'))
,('Shanghai Pudong International Airport','PVG', (SELECT id FROM city WHERE name = 'Shanghai'),(SELECT name FROM country WHERE name = 'China'))
,('Indira Gandhi International Airport','DEL', (SELECT id FROM city WHERE name = 'New Delhi'),(SELECT name FROM country WHERE name = 'India'))
,('Suvarnabhumi Airport','BKK', (SELECT id FROM city WHERE name = 'Bangkok'),(SELECT name FROM country WHERE name = 'Thailand'))
,('Leonardo da Vinci-Fiumicino Airport','FCO', (SELECT id FROM city WHERE name = 'Rome'),(SELECT name FROM country WHERE name = 'Italy'))
,('San Francisco International Airport','SFO', (SELECT id FROM city WHERE name = 'San Francisco'),(SELECT name FROM country WHERE name = 'USA'))
,('Jorge Chávez International Airport','LIM', (SELECT id FROM city WHERE name = 'Lima'),(SELECT name FROM country WHERE name = 'Peru'))
,('Kuala Lumpur International Airport','KUL', (SELECT id FROM city WHERE name = 'Kuala Lumpur'),(SELECT name FROM country WHERE name = 'Malaysia'))
,('Copenhagen Airport','CPH', (SELECT id FROM city WHERE name = 'Copenhagen'),(SELECT name FROM country WHERE name = 'Denmark'))
,('Vancouver International Airport','YVR', (SELECT id FROM city WHERE name = 'Vancouver'),(SELECT name FROM country WHERE name = 'Canada'))
,('Athens International Airport','ATH', (SELECT id FROM city WHERE name = 'Athens'),(SELECT name FROM country WHERE name = 'Greece'))
,('Dubai World Central-Al Maktoum International Airport','DWC', (SELECT id FROM city WHERE name = 'Dubai'),(SELECT name FROM country WHERE name = 'UAE'))
,('Adolfo Suárez Madrid–Barajas Airport','MAD', (SELECT id FROM city WHERE name = 'Madrid'),(SELECT name FROM country WHERE name = 'Spain'))
,('Jomo Kenyatta International Airport','NBO', (SELECT id FROM city WHERE name = 'Nairobi'),(SELECT name FROM country WHERE name = 'Kenya'))
,('Hamad International Airport','DOH', (SELECT id FROM city WHERE name = 'Doha'),(SELECT name FROM country WHERE name = 'Qatar'))
;
